# Generated by Django 2.2 on 2019-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_blob', models.BinaryField()),
                ('full_blob', models.BinaryField()),
                ('uploader_id', models.IntegerField()),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
