# Generated by Django 2.2 on 2019-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190516_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploader_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
