# Generated by Django 2.2 on 2019-05-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190516_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='full_blob',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='preview_blob',
        ),
    ]
