# Generated by Django 2.2 on 2019-05-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190516_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
